### ISSUE TITLE
Unable to listpids of newer sandboxie versions

### ISSUE THREAD

**Issue by nubonics** [nedsociety/pysandboxie#12]
About a year ago, I was able to use the listpids() feature that you added, however, this feature has seemed to die in the newer versions of sandboxie [ when sandboxie is upgraded to the latest version, the listpids method in pysandboxie no longer works. ]

**Comment by nedsociety** [comment]
I cannot reproduce the issue in the latest sbie 1.3.2:

```py
>>> import sandboxie
>>> sbie = sandboxie.Sandboxie()
>>> proc = sbie.execute(['notepad.exe'], 'DefaultBox')
>>> sbie.listpids('DefaultBox') 
[442224, 439536, 431452, 443156]
>>>
```

- What's your sandboxie version?
- Did you call `listpids()` without argument? Because that would just show the list of PIDs spawned in the DefaultBox, not every PIDs that are sandboxed.
- If you run notepad in DefaultBox then type following command in the shell, what does it show?
```
{path to the Sandboxie installation}\Start.exe /box:DefaultBox /listpids | more
```
- Might be related to #11 if it shows a python exception.

**Comment by nubonics** [comment]
Saving the Sandboxie.ini file with the encoding you mentioned in the other issue I raised solved this problem as well.

Thank you so much!!!

& For creating this library, cant thank you enough!
& For your speedy responses! Awesome!
